-- return {
--   "olivercederborg/poimandres.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.cmd("colorscheme poimandres")
--   end,
--   setup = {
--     disable_background = true,
--   },
-- }
return {}
