-- return {
--
--   {
--     "folke/tokyonight.nvim",
--     -- opts = {
--     --   transparent = true,
--     --   styles = {
--     --     sidebars = "transparent",
--     --     float = "transparent",
--     --   },
--     -- },
--   },
--   -- Configure lazyvim to load theme
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "tokyonight",
--     },
--   },
-- }
return {}
